// src/services/flammyExplainer.ts

import { openaiService } from './openaiService';

export async function generateHealthExplanation(
  userQuestion: string,
  conversationHistory: Array<{role: string, content: string}> = []
) {
  try {
    console.log('Processing question:', userQuestion);
    
    // Generate response using OpenAI only
    const openaiResponse = await openaiService.generateHealthResponse(
      userQuestion,
      conversationHistory
    );
    
    console.log('Generated OpenAI response');
    
    return {
      summary: openaiResponse,
      evidenceLevel: "ai_assisted",
      sources: [],
      explanation: "Response generated by AI health assistant",
      uncertainty: "",
      solutions: "",
    };
  } catch (error) {
    console.error('Error in generateHealthExplanation:', error);
    
    // Fallback to local response if OpenAI fails
    const fallbackResponse = generateHealthResponse(userQuestion);
    
    return {
      summary: "I'm really sorry, but I'm having some technical difficulties right now. 😔 Please don't let that stop you from taking care of your health! If you're dealing with something concerning, it's always best to reach out to a healthcare professional.\n\nFeel free to try asking me again in a moment - I'll be here to help as soon as I can. Your health matters, and I want to support you in any way I can! 💙",
      evidenceLevel: "general",
      sources: [],
      explanation: "Fallback response - AI service unavailable",
      uncertainty: "Currently unable to access AI service",
      solutions: "",
    };
  }
}

function generateHealthResponse(question: string) {
  const lowerQuestion = question.toLowerCase();
  
  // Handle greetings and social interactions
  const greetings = ['how are you', 'hello', 'hi', 'hey', 'good morning', 'good afternoon', 'good evening', 'thanks', 'thank you', 'bye', 'goodbye'];
  if (greetings.some(greeting => lowerQuestion.includes(greeting))) {
    return getGreetingResponse(lowerQuestion);
  }
  
  // Handle symptom descriptions with empathy and clarifying questions
  if (lowerQuestion.includes('hurt') || lowerQuestion.includes('pain') || lowerQuestion.includes('ache')) {
    return handlePainSymptoms(lowerQuestion);
  }
  
  if (lowerQuestion.includes('stomach') || lowerQuestion.includes('belly') || lowerQuestion.includes('abdomen')) {
    return handleStomachIssues(lowerQuestion);
  }
  
  if (lowerQuestion.includes('headache') || lowerQuestion.includes('head') && lowerQuestion.includes('hurt')) {
    return handleHeadache(lowerQuestion);
  }
  
  if (lowerQuestion.includes('fever') || lowerQuestion.includes('hot') || lowerQuestion.includes('temperature')) {
    return handleFever(lowerQuestion);
  }
  
  if (lowerQuestion.includes('tired') || lowerQuestion.includes('fatigue') || lowerQuestion.includes('exhausted')) {
    return handleFatigue(lowerQuestion);
  }
  
  if (lowerQuestion.includes('nausea') || lowerQuestion.includes('sick') || lowerQuestion.includes('vomit')) {
    return handleNausea(lowerQuestion);
  }
  
  if (lowerQuestion.includes('cough') || lowerQuestion.includes('cold') || lowerQuestion.includes('flu')) {
    return handleRespiratory(lowerQuestion);
  }
  
  if (lowerQuestion.includes('sleep') || lowerQuestion.includes('insomnia') || lowerQuestion.includes('can\'t sleep')) {
    return handleSleep(lowerQuestion);
  }
  
  if (lowerQuestion.includes('stress') || lowerQuestion.includes('anxiety') || lowerQuestion.includes('worry')) {
    return handleStress(lowerQuestion);
  }
  
  // Default helpful response
  return "I'm here to help with general health questions. Could you tell me more about what you're experiencing or what health topic you'd like to discuss?";
}

function getGreetingResponse(question: string) {
  if (question.includes('how are you')) {
    return "I'm doing well, thank you! I'm here to help you with health questions and provide general guidance. What can I help you with today?";
  }
  if (question.includes('hello') || question.includes('hi') || question.includes('hey')) {
    return "Hello! I'm here to help with health questions and provide supportive guidance. How can I assist you today?";
  }
  if (question.includes('good morning')) {
    return "Good morning! How can I help you with your health questions today?";
  }
  if (question.includes('good afternoon')) {
    return "Good afternoon! What health questions can I help you with?";
  }
  if (question.includes('good evening')) {
    return "Good evening! How can I assist you with health concerns tonight?";
  }
  if (question.includes('thanks') || question.includes('thank you')) {
    return "You're welcome! Is there anything else I can help you with?";
  }
  if (question.includes('bye') || question.includes('goodbye')) {
    return "Goodbye! Take care, and feel free to come back if you have any health questions.";
  }
  return "Hello! I'm here to help with health questions. How can I assist you?";
}

function handlePainSymptoms(question: string) {
  let response = "I understand you're experiencing pain. That can be really uncomfortable. ";
  
  if (question.includes('chest')) {
    response += "Chest pain should always be taken seriously. Can you tell me more about what the pain feels like - is it sharp, dull, pressure, or burning? Does it change with breathing or movement? Any chest pain that's severe, crushing, or accompanied by shortness of breath, sweating, or pain radiating to your arm or jaw needs immediate medical attention.";
  } else if (question.includes('back')) {
    response += "Back pain is very common and can range from mild to severe. Where exactly is your back hurting - upper, middle, or lower? What does the pain feel like, and does anything make it better or worse? Have you had any recent injuries or changes in your daily activities?";
  } else if (question.includes('joint') || question.includes('knee') || question.includes('hip')) {
    response += "Joint pain can be really frustrating. Which joints are affected? Is there any swelling, redness, or warmth? Does the pain worsen with movement or is it worse in the morning? These details can help understand what might be happening.";
  } else {
    response += "Pain is your body's way of signaling that something needs attention. Can you tell me more about where the pain is, what it feels like, when it started, and if anything makes it better or worse?";
  }
  
  response += " For general pain management, gentle movement, proper posture, and over-the-counter pain relievers may help, but persistent or severe pain should be evaluated by a healthcare provider.";
  
  return response;
}

function handleStomachIssues(question: string) {
  let response = "Stomach issues can be really uncomfortable and concerning. ";
  
  if (question.includes('hurt') || question.includes('pain') || question.includes('ache')) {
    response += "Can you tell me more about the stomach pain - where exactly is it located (upper, lower, left, right), what does it feel like (sharp, dull, cramping), and when did it start? Is it related to eating, or does it happen at specific times?";
  } else {
    response += "What specific stomach symptoms are you experiencing - pain, bloating, nausea, burning, or changes in bowel movements?";
  }
  
  response += " Common possibilities include indigestion, gas, constipation, or food-related issues. For mild stomach discomfort, staying hydrated, eating smaller meals, and avoiding trigger foods may help. However, severe pain, persistent symptoms, or additional symptoms like fever, vomiting, or bloody stools should be evaluated by a healthcare provider.";
  
  return response;
}

function handleHeadache(question: string) {
  let response = "Headaches can really disrupt your day. ";
  response += "Can you tell me more about your headache - where is it located (forehead, temples, back of head), what type of pain is it (throbbing, pressure, sharp), and how often do you get them? ";
  response += "Have you noticed any triggers like stress, certain foods, lack of sleep, or changes in your routine?";
  
  response += " Common types include tension headaches (often feel like a band around your head), migraines (often throbbing and may affect one side), and sinus headaches. For mild headaches, rest, hydration, and over-the-counter pain relievers may help. However, severe headaches, headaches that are accompanied by fever, stiff neck, confusion, or vision changes, or headaches that are changing in pattern should be evaluated by a healthcare provider.";
  
  return response;
}

function handleFever(question: string) {
  let response = "I understand you're concerned about fever. ";
  response += "Have you been able to check your temperature? How high is it, and are there any other symptoms like chills, body aches, sweating, or feeling generally unwell?";
  
  response += " Fever is your body's natural response to fighting infections. For mild fever (under 102°F/38.9°C) in adults, rest, staying hydrated, and over-the-counter fever reducers may help. However, high fever (over 103°F/39.4°C), fever that lasts more than 3 days, or fever accompanied by severe headache, stiff neck, confusion, difficulty breathing, or other concerning symptoms should be evaluated by a healthcare provider.";
  
  return response;
}

function handleFatigue(question: string) {
  let response = "Feeling tired can really affect your daily life. ";
  response += "How long have you been feeling this way? Does the fatigue improve with rest, or is it constant? Are you getting enough sleep, and have you noticed any changes in your appetite, mood, or stress levels?";
  
  response += " Fatigue can have many causes - poor sleep quality, stress, nutritional deficiencies, or underlying medical conditions. For general fatigue, ensuring adequate sleep (7-9 hours), maintaining a balanced diet, staying hydrated, regular exercise, and stress management may help. However, persistent fatigue that doesn't improve with lifestyle changes or is accompanied by other concerning symptoms should be discussed with a healthcare provider.";
  
  return response;
}

function handleNausea(question: string) {
  let response = "Nausea can be very uncomfortable. ";
  response += "When did the nausea start, and is it related to eating anything specific? Are there any other symptoms like vomiting, dizziness, fever, or stomach pain?";
  
  response += " Nausea can have many causes - digestive issues, infections, motion sickness, or other conditions. For mild nausea, sipping clear fluids, eating small bland meals, ginger tea, and getting fresh air may help. However, persistent nausea, vomiting that lasts more than 24 hours, or nausea accompanied by severe abdominal pain, fever, or signs of dehydration should be evaluated by a healthcare provider.";
  
  return response;
}

function handleRespiratory(question: string) {
  let response = "Respiratory symptoms can be really concerning. ";
  response += "How long have you been experiencing these symptoms? Is your cough dry or productive (bringing up mucus), and are there other symptoms like fever, body aches, sore throat, or congestion?";
  
  response += " Coughs and colds are usually viral and resolve on their own. For symptom relief, staying hydrated, using a humidifier, honey for cough (over 1 year old), and getting plenty of rest may help. However, high fever, difficulty breathing, chest pain, or symptoms lasting more than 10 days should be evaluated by a healthcare provider.";
  
  return response;
}

function handleSleep(question: string) {
  let response = "Sleep problems can be really frustrating and affect everything else in your life. ";
  response += "What specific sleep issues are you having - trouble falling asleep, waking up frequently, or waking up too early? How long has this been going on, and have there been any recent changes in your routine, stress levels, or environment?";
  
  response += " Sleep issues can be related to stress, poor sleep habits, environment, or underlying conditions. For better sleep, maintaining a consistent sleep schedule, creating a relaxing bedtime routine, keeping your bedroom cool and dark, avoiding screens before bed, limiting caffeine, and regular exercise may help. However, persistent sleep problems that affect your daily functioning should be discussed with a healthcare provider.";
  
  return response;
}

function handleStress(question: string) {
  let response = "Stress can really take a toll on both your mind and body. ";
  response += "What's been causing you stress lately? Are you experiencing physical symptoms like muscle tension, headaches, digestive issues, or sleep problems?";
  
  response += " Stress is very common and can manifest in many ways. For stress management, regular exercise, deep breathing exercises, meditation, maintaining social connections, good sleep, and time management techniques may help. However, if stress is overwhelming, affecting your daily functioning, or causing significant physical symptoms, it may be helpful to talk with a healthcare provider or mental health professional.";
  
  return response;
}

/**
 * Supportive Health Assistant
 * Provides empathetic, conversational health guidance
 * Can ask clarifying questions and acknowledge symptoms
 * Offers general self-care guidance and suggests when professional care may be appropriate
 */
